version: '3'

services:
  app:
    build:
      context: .
      dockerfile: ./containers/parity/Dockerfile
    volumes:
      - ./containers/parity/data:/root/.local/share/io.parity.ethereum
    ports:
      - "8545:8545"
      - "18545:18545"
      - "30303/udp"
      - "30303/tcp"
      - "5001:5001"
      - "8082:8082"
      - "8180:8180"
      - "8546:8546"
    stdin_open: true
    tty: true
    command: /root/parity-ethereum/target/release/parity --config /root/parity-ethereum/containers/parity/config.toml --pruning fast --jsonrpc-interface all --jsonrpc-hosts all --warp-barrier 4950000